defaults:
  - train
  - _self_

n_train: 5_000

mesh:
  _target_: pinnstf2.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      num_sample: ${n_train}
      solution:
        - u
        - v
      collection_points:
        - f_u
        - f_v

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - u
        - v
        - p

# Now the test dataset uses a different time index (idx_t_test)
test_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - u
        - v
        - p

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - u
        - v
        - p

net:
  _target_: pinnstf2.models.FCN
  layers: [3, 20, 20, 20, 20, 20, 20, 20, 20, 20, 2] # Added extra layer
  output_names:
    - psi
    - p
  activation: "tanh"  # or "tanh" YY, "sigmoid" YY, "relu" XX, "swish" YY, "softsign" XX, "softplus" YY.

model:
  optimizer: ${optimizer}
  loss_fn: sse # sse (default) , mse, mae, huber.
  extra_variables:
    l1: 0.0
    l2: 0.0

# Optimizer configuration provided
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 0.001
# optimizer:
#   _target_: tensorflow.keras.optimizers.Adagrad
#   learning_rate: 0.01
#   initial_accumulator_value: 0.1
# optimizer:
#   _target_: tensorflow.keras.optimizers.RMSprop
#   learning_rate: 0.001
#   rho: 0.9
#   momentum: 0.0
#   epsilon: 1e-7
# optimizer:
#   _target_: tensorflow.keras.optimizers.Nadam
#   learning_rate: 0.002
#   beta_1: 0.9
#   beta_2: 0.999
#   epsilon: 1e-7

trainer:
  max_epochs: 250000
  check_val_every_n_epoch: 250001
  default_root_dir: ${tensorboard.log_dir}  # Pass log directory to enable Trainer's TensorBoard.

train: true
val: true
test: true
optimized_metric:
  error:
    - u
    - v
    - p
  test: # Comment it out if you dont want test
    - u
    - v
    - p
  extra_variables:
    - l1
    - l2

plotting:
  _target_: pinnstf2.utils.plot_navier_stokes
  _partial_: true

task_name: navier_stokes

hydra:
  searchpath:
    - pkg://pinnstf2/conf

tensorboard:
  log_dir: ${paths.output_dir}/logs
  histogram_freq: 1
  write_graph: true
  update_freq: epoch